from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class CaptionTheme:
    label: str
    font: str
    font_size: int
    primary: str
    active: str
    outline: str = "&H00000000"
    back: str = "&H80000000"
    bold: bool = True
    border_style: int = 1
    outline_size: float = 6.0
    shadow: float = 0.0
    alignment: int = 5
    margin_v: int = 120
    uppercase: bool = False
    max_words: int = 4


CAPTION_THEMES: dict[str, CaptionTheme] = {
    "classic_yellow": CaptionTheme(
        "Classic Yellow", "Arial Black", 92, "&H00FFFFFF", "&H0000FFFF", outline_size=7, max_words=4
    ),
    "clean_white": CaptionTheme(
        "Clean White", "Arial", 88, "&H00FFFFFF", "&H00FFFF00", outline_size=5, shadow=2, max_words=5
    ),
    "tiktok_pop": CaptionTheme(
        "TikTok Pop", "Arial Black", 94, "&H00FFFFFF", "&H00FF4FD8", outline_size=7, shadow=2, max_words=4
    ),
    "mrbeast_punch": CaptionTheme(
        "Punchy Creator", "Impact", 104, "&H00FFFFFF", "&H0000FFFF", outline_size=9, uppercase=True, max_words=3
    ),
    "neon_green": CaptionTheme(
        "Neon Green", "Arial Black", 94, "&H00FFFFFF", "&H0000FF57", outline_size=7, shadow=2, max_words=4
    ),
    "electric_blue": CaptionTheme(
        "Electric Blue", "Trebuchet MS", 92, "&H00FFFFFF", "&H00FFCC33", outline_size=6, shadow=2, max_words=4
    ),
    "red_alert": CaptionTheme(
        "Red Alert", "Impact", 100, "&H00FFFFFF", "&H003C3CFF", outline_size=8, uppercase=True, max_words=3
    ),
    "minimal_box": CaptionTheme(
        "Minimal Box", "Segoe UI Semibold", 82, "&H00FFFFFF", "&H0000FFFF", back="&H68000000",
        border_style=3, outline_size=1.5, shadow=0, alignment=2, margin_v=250, max_words=5
    ),
    "karaoke": CaptionTheme(
        "Karaoke", "Verdana", 86, "&H00FFFFFF", "&H0000FFFF", outline_size=5, alignment=2, margin_v=280, max_words=4
    ),
    "story_calm": CaptionTheme(
        "Story Calm", "Trebuchet MS", 82, "&H00FFFFFF", "&H00FFCC88", outline_size=5, shadow=1, alignment=2,
        margin_v=260, max_words=6
    ),
}


def theme_choices() -> list[tuple[str, str]]:
    return [(theme.label, key) for key, theme in CAPTION_THEMES.items()]


def format_time(seconds: float) -> str:
    total_centiseconds = max(0, round(float(seconds) * 100))
    hours, remainder = divmod(total_centiseconds, 360_000)
    minutes, remainder = divmod(remainder, 6_000)
    whole_seconds, centiseconds = divmod(remainder, 100)
    return f"{hours}:{minutes:02}:{whole_seconds:02}.{centiseconds:02}"


def _ass_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}").replace("\n", " ").strip()


def _extract_words(data: dict[str, Any]) -> list[dict[str, Any]]:
    words = data.get("word_segments") or []
    if not words:
        for segment in data.get("segments", []):
            words.extend(segment.get("words", []))
    return [
        word
        for word in words
        if word.get("word") is not None and word.get("start") is not None and word.get("end") is not None
    ]


def _chunk_words(words: list[dict[str, Any]], max_words: int, pause_threshold: float) -> list[list[dict[str, Any]]]:
    chunks: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    for index, word in enumerate(words):
        current.append(word)
        is_last = index == len(words) - 1
        if is_last:
            chunks.append(current)
            break
        next_word = words[index + 1]
        gap = float(next_word["start"]) - float(word["end"])
        if len(current) >= max_words or gap >= pause_threshold:
            chunks.append(current)
            current = []
    return chunks


def _header(theme: CaptionTheme, width: int, height: int) -> str:
    bold = -1 if theme.bold else 0
    return f"""[Script Info]
; Generated by Reddit Romantics Automation
Title: Styled word-highlight captions
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: {width}
PlayResY: {height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{theme.font},{theme.font_size},{theme.primary},{theme.active},{theme.outline},{theme.back},{bold},0,0,0,100,100,0,0,{theme.border_style},{theme.outline_size},{theme.shadow},{theme.alignment},60,60,{theme.margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""



def trim_whisperx_json(
    input_file: str | Path,
    output_file: str | Path,
    end_time: float,
) -> Path:
    """Create a transcript containing only timestamps before ``end_time``.

    Shorts always begin at the start of the story, so timestamps do not need to be shifted.
    """
    if end_time <= 0:
        raise ValueError("Short end time must be greater than zero.")

    input_path = Path(input_file)
    output_path = Path(output_file)
    with input_path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    def keep_word(word: dict[str, Any]) -> bool:
        start = word.get("start")
        return start is not None and float(start) < end_time

    def trim_word(word: dict[str, Any]) -> dict[str, Any]:
        result = dict(word)
        if result.get("end") is not None:
            result["end"] = min(float(result["end"]), end_time)
        return result

    if isinstance(data.get("word_segments"), list):
        data["word_segments"] = [trim_word(word) for word in data["word_segments"] if keep_word(word)]

    trimmed_segments: list[dict[str, Any]] = []
    for segment in data.get("segments", []) or []:
        start = segment.get("start")
        if start is None or float(start) >= end_time:
            continue
        item = dict(segment)
        if item.get("end") is not None:
            item["end"] = min(float(item["end"]), end_time)
        if isinstance(item.get("words"), list):
            item["words"] = [trim_word(word) for word in item["words"] if keep_word(word)]
        trimmed_segments.append(item)
    if "segments" in data:
        data["segments"] = trimmed_segments

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path

def convert_whisperx_json_to_ass(
    input_file: str | Path,
    output_file: str | Path,
    theme_name: str = "classic_yellow",
    max_words: int | None = None,
    pause_threshold: float = 0.5,
    width: int = 1080,
    height: int = 1920,
) -> Path:
    input_path = Path(input_file)
    output_path = Path(output_file)
    theme = CAPTION_THEMES.get(theme_name)
    if theme is None:
        raise ValueError(f"Unknown caption theme: {theme_name}")

    with input_path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    words = _extract_words(data)
    if not words:
        raise ValueError(f"WhisperX JSON contains no word-level timestamps: {input_path}")

    words_per_chunk = int(max_words or theme.max_words)
    chunks = _chunk_words(words, words_per_chunk, float(pause_threshold))
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(_header(theme, width, height))
        for chunk in chunks:
            display_words = [_ass_escape(str(word["word"])) for word in chunk]
            if theme.uppercase:
                display_words = [word.upper() for word in display_words]

            for index, word in enumerate(chunk):
                start = float(word["start"])
                if index < len(chunk) - 1:
                    end = max(float(word["end"]), float(chunk[index + 1]["start"]))
                else:
                    end = float(word["end"])
                if end <= start:
                    end = start + 0.05

                pieces: list[str] = []
                for word_index, text in enumerate(display_words):
                    if word_index == index:
                        pieces.append(f"{{\\1c{theme.active}}}{text}{{\\1c{theme.primary}}}")
                    else:
                        pieces.append(text)
                line = " ".join(pieces)
                handle.write(
                    f"Dialogue: 0,{format_time(start)},{format_time(end)},Default,,0,0,0,,{line}\n"
                )

    return output_path
