#!/usr/bin/env python3
import re
import sys
import os

def vtt_to_ass(vtt_file, ass_file=None):
    """
    Convert WebVTT file to ASS format, highlighting text in <u> tags with yellow background
    """
    if ass_file is None:
        # Create output filename by replacing extension
        ass_file = os.path.splitext(vtt_file)[0] + ".ass"
    
    # Read VTT file
    with open(vtt_file, 'r', encoding='utf-8') as f:
        vtt_content = f.read()
    
    # Parse VTT content
    lines = vtt_content.split('\n')
    entries = []
    
    i = 0
    # Skip header (WEBVTT)
    while i < len(lines) and not re.match(r'\d{2}:\d{2}.\d{3} --> \d{2}:\d{2}.\d{3}', lines[i]):
        i += 1
    
    while i < len(lines):
        # Find timestamp lines
        if re.match(r'\d{2}:\d{2}.\d{3} --> \d{2}:\d{2}.\d{3}', lines[i]):
            timestamp = lines[i]
            text = ""
            i += 1
            
            # Collect text until next timestamp or empty line
            while i < len(lines) and not re.match(r'\d{2}:\d{2}.\d{3} --> \d{2}:\d{2}.\d{3}', lines[i]) and lines[i].strip():
                text += lines[i]
                i += 1
            
            # Extract timestamps
            start_time, end_time = timestamp.split(' --> ')
            entries.append((start_time, end_time, text))
        else:
            i += 1
    
    # Create ASS content
    ass_content = generate_ass_file(entries)
    
    # Write ASS file
    with open(ass_file, 'w', encoding='utf-8') as f:
        f.write(ass_content)
    
    return ass_file

def generate_ass_file(entries):
    """
    Generate ASS file content from parsed entries
    """
    # ASS file header with style definitions - note Alignment=5 for center screen
    header = """[Script Info]
; Script generated by VTT to ASS Converter
Title: Converted VTT to ASS
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 2560
PlayResY: 1440

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,5,10,10,10,1
Style: HighlightBox,Arial,48,&H00000000,&H00000000,&H0000FFFF,&H0000FFFF,-1,0,0,0,100,100,0,0,3,0,0,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    
    events = []
    
    for start_time, end_time, text in entries:
        # Convert timestamps from VTT (00:01.634) to ASS format (0:00:01.63)
        start_ass = convert_timestamp(start_time)
        end_ass = convert_timestamp(end_time)
        
        # Process text to convert <u> tags to ASS formatting with yellow background
        processed_text = process_text_with_highlighting(text)
        
        # Create event line - add \an5 to center the text on screen
        event = f"Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{{\\an5}}{processed_text}"
        events.append(event)
    
    return header + '\n'.join(events)

def convert_timestamp(vtt_timestamp):
    """
    Convert VTT timestamp (00:01.634) to ASS timestamp (0:00:01.63)
    """
    # Handle VTT timestamp format
    if '.' in vtt_timestamp:
        parts = vtt_timestamp.split('.')
        main_time = parts[0]
        milliseconds = parts[1][:2]  # Take only 2 digits for centiseconds
        
        # Pad milliseconds if needed
        if len(milliseconds) == 1:
            milliseconds += '0'
        
        # Add hour if missing (VTT might have MM:SS.ms format)
        if main_time.count(':') == 1:
            main_time = '00:' + main_time
        
        return f"{main_time}.{milliseconds}"
    return vtt_timestamp

def process_text_with_highlighting(text):
    """
    Convert <u> tags to ASS formatting with yellow background
    """
    # Pattern to find text within <u> tags
    pattern = r'<u>(.*?)</u>'
    
    # Function to replace matched text with ASS formatting
    def replace_with_highlight(match):
        highlighted_text = match.group(1)
        # Simplified version - just yellow background without scaling effects
        return f"{{\\1c&H000000&\\3c&H00FFFF&\\bord8\\shad0}}{{\\3a&H00&}}{highlighted_text}{{\\r}}"
    
    # Replace all occurrences of <u> tags with ASS formatting
    processed_text = re.sub(pattern, replace_with_highlight, text)
    
    return processed_text

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python vtt_to_ass.py input.vtt [output.ass]")
        sys.exit(1)
    
    vtt_file = sys.argv[1]
    
    if len(sys.argv) > 2:
        ass_file = sys.argv[2]
        output_file = vtt_to_ass(vtt_file, ass_file)
    else:
        output_file = vtt_to_ass(vtt_file)
    
    print(f"Conversion complete. Output file: {output_file}")