import json
import argparse
from datetime import timedelta

def format_time(seconds):
    """Convert seconds to ASS time format (H:MM:SS.cc)"""
    hours = int(seconds / 3600)
    minutes = int((seconds % 3600) / 60)
    seconds = seconds % 60
    centiseconds = int((seconds - int(seconds)) * 100)
    return f"{hours}:{minutes:02}:{int(seconds):02}.{centiseconds:02}"

def create_ass_header(font_name="Verdana"):
    """Create the header section of ASS file with specified font"""
    return f"""[Script Info]
; Script generated by WhisperX to ASS Converter
Title: Auto-generated ASS subtitle file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 2560
PlayResY: 1440

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,6,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

def whisperx_json_to_natural_ass(input_file, output_file, max_words=5, pause_threshold=0.7, font_size=96, font_name="Verdana"):
    """
    Convert WhisperX JSON output to ASS subtitle file with natural speech pauses
    
    Args:
        input_file: Path to WhisperX JSON output file
        output_file: Path to output ASS file
        max_words: Maximum words per line (default: 5)
        pause_threshold: Time gap in seconds that defines a pause (default: 0.7)
        font_size: Font size for subtitles (default: 96)
        font_name: Font to use (default: Verdana)
    """
    # Read WhisperX JSON output
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Extract all words with their timing info from the JSON
    all_words = data.get('word_segments', [])
    if not all_words and 'segments' in data:
        # If there's no word_segments, try to get from segments
        for segment in data['segments']:
            if 'words' in segment:
                all_words.extend(segment['words'])
    
    # Group words into natural chunks based on pauses
    chunks = []
    current_chunk = []
    
    for i, word in enumerate(all_words):
        # Add the current word to the chunk
        current_chunk.append(word)
        
        # Check if this is the last word
        if i == len(all_words) - 1:
            if current_chunk:
                chunks.append(current_chunk)
            break
        
        # Check if we need to start a new chunk based on:
        # 1. The time gap to the next word exceeds the pause threshold
        # 2. We've reached the maximum word count for this chunk
        next_word = all_words[i + 1]
        time_gap = next_word['start'] - word['end']
        
        if time_gap >= pause_threshold or len(current_chunk) >= max_words:
            chunks.append(current_chunk)
            current_chunk = []
    
    # Create ASS file with header
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(create_ass_header(font_name))
        
        # Process each natural chunk
        for chunk in chunks:
            if not chunk:
                continue
            
            # Create chunk text (all words together)
            chunk_text = ' '.join(word['word'].strip() for word in chunk).strip()
            
            # Generate all events for this chunk
            events = []
            
            # For each word in the chunk
            for idx, word in enumerate(chunk):
                # Create highlighted version for current word with proper font
                # First apply font settings to the entire line
                highlighted_text = f"{{\\fn{font_name}}}{{\\fs{font_size}}}{{\\b1}}{{\\an5}}"
                
                # Then add each word, highlighting the current one
                for w_idx, w in enumerate(chunk):
                    if w_idx > 0:
                        highlighted_text += " "
                    
                    w_text = w['word'].strip()
                    if w_idx == idx:  # This is the word to highlight
                        highlighted_text += f"{{\\1c&H00FFFF&}}{w_text}{{\\r}}{{\\fn{font_name}}}{{\\fs{font_size}}}{{\\b1}}"
                    else:
                        highlighted_text += w_text
                
                # Add highlighted word event
                events.append({
                    'start': word['start'],
                    'end': word['end'],
                    'text': highlighted_text
                })
                
                # Add non-highlighted text in small gaps between words (but within the same chunk)
                if idx < len(chunk) - 1:
                    next_word = chunk[idx + 1]
                    if word['end'] < next_word['start']:
                        events.append({
                            'start': word['end'],
                            'end': next_word['start'],
                            'text': f"{{\\fn{font_name}}}{{\\fs{font_size}}}{{\\b1}}{{\\an5}}{chunk_text}"
                        })
            
            # Sort events by start time
            events.sort(key=lambda x: x['start'])
            
            # Write all events
            for event in events:
                start_time_ass = format_time(event['start'])
                end_time_ass = format_time(event['end'])
                dialogue_line = f"Dialogue: 0,{start_time_ass},{end_time_ass},Default,,0,0,0,,{event['text']}\n"
                f.write(dialogue_line)
    
    print(f"Conversion complete! Output saved to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert WhisperX JSON to ASS subtitles based on natural speech pauses")
    parser.add_argument("input", help="Input WhisperX JSON file")
    parser.add_argument("output", help="Output ASS file")
    parser.add_argument("--max-words", type=int, default=5, help="Maximum words per line (default: 5)")
    parser.add_argument("--pause", type=float, default=0.7, help="Pause threshold in seconds (default: 0.7)")
    parser.add_argument("--font-size", type=int, default=96, help="Font size for subtitles (default: 96)")
    parser.add_argument("--font", type=str, default="Verdana", help="Font name (default: Verdana)")
    
    args = parser.parse_args()
    
    whisperx_json_to_natural_ass(args.input, args.output, args.max_words, args.pause, args.font_size, args.font)